### PR TITLE
replaced mutex swap by mutex copy in array move operator

### PR DESCRIPTION
**Pull request by vincentberenz**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

On ubuntu 18.04 (newer version of compiler compared to 16.04), shared memory mutex can no longer be swapped (no idea why. Compilation error). Replaced the swap by a hard copy.

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."

## How I Tested

Ran the unit tests and the demos

### CODE REVIEW

**Comment by vincentberenz** [comment]
this was for compilation on 18.04. But apparently things compile fine on 18.04 / c++17 without this change.

**Comment by vincentberenz** [comment]
this was for compilation on 18.04. But apparently things compile fine on 18.04 / c++17 without this change.
